#include "neocore.h"

void test_v2_type_patterns() {
    // V2 type patterns that were removed in v3

    // These typedefs were removed in v3 - should cause compilation errors
    Hex_Color color = "FF";
    Hex_Packed_Color packedColor = "FFFF";

    // V2 Vec2short type (replaced by Position in v3)
    Vec2short oldPosition;
    oldPosition.x = 10;
    oldPosition.y = 20;
}

void test_v2_logging_functions() {
    // V2 logging functions with changed signatures in v3

    Hex_Color color = "FF";
    Hex_Packed_Color packedColor = "FFFF";
    Vec2short position = {10, 20};

    // These logging functions have changed signatures in v3
    nc_log_rgb16(color);
    nc_log_packed_color16(packedColor);
    nc_log_vec2short(position);
}

void test_v2_position_functions() {
    // V2 position functions that return values (v3 uses output parameters)

    // V2 pattern: functions return Vec2short
    Vec2short pos1 = nc_get_position_gfx_animated_sprite(0);
    Vec2short pos2 = nc_get_position_gfx_picture(0);
    Vec2short pos3 = nc_get_position_gfx_scroller(0);
}

void test_v2_palette_functions() {
    // V2 palette manager functions with old signatures

    // V2 pattern: missing palette bank parameter (v3 requires it)
    nc_load_palettes();
    nc_get_palette(0);
}

void test_v2_sprite_functions() {
    // V2 sprite manager functions with old signatures

    // V2 pattern: missing sprite bank parameter (v3 requires it)
    nc_load_sprites();
}

void test_v2_sound_functions() {
    // V2 sound functions that may have changed in v3

    // V2 pattern: old sound function signature
    nc_load_sound("test.wav");

    // V2 ADPCM functions (verify v3 compatibility)
    nc_adpcm_play(0);
    nc_adpcm_stop();
    nc_adpcm_pause();
}

void test_v2_memory_functions() {
    // V2 memory management patterns

    void* ptr = nc_malloc(1024);
    nc_free(ptr);
}

void test_v2_constants_and_macros() {
    // V2 constants and macros

    int width = CD_WIDTH;
    int height = CD_HEIGHT;

    // V2 macro (replaced by POSITION macro in v3)
    Vec2short pos = VEC2SHORT(10, 20);
}

void test_v2_datlib_patterns() {
    // DATlib 0.2 patterns (DATlib 0.3 required for v3)

    // V2 DATlib 0.2 physic sprite patterns
    // Note: These would be generated by DATlib, not hand-written
    // GFX_AnimatedSprite_example_physic sprite;
    // nc_load_gfx_animated_sprite_example_physic(&sprite);
}

int main() {
    nc_log("=== Testing all v2 to v3 migration patterns ===");

    // Test all v2 patterns that need migration
    test_v2_type_patterns();
    test_v2_logging_functions();
    test_v2_position_functions();
    test_v2_palette_functions();
    test_v2_sprite_functions();
    test_v2_sound_functions();
    test_v2_memory_functions();
    test_v2_constants_and_macros();
    test_v2_datlib_patterns();

    nc_log("=== v2 pattern testing completed ===");
    return 0;
}
